export const ADD_TO_PURCHASE_CART = 'ADD_TO_PURCHASE_CART';
export const REMOVE_FROM__PURCHASE_CART = 'REMOVE_FROM__PURCHASE_CART';
export const ADD_PURCHASE_ITEM_FROM_TEXTFIELD='ADD_PURCHASE_ITEM_FROM_TEXTFIELD';
export const CLEAR_PURCHASE_CART = 'CLEAR_PURCHASE_CART';
export const UPDATE_PURCHASE_CART = 'UPDATE_PURCHASE_CART';